main: me.im2epic4u.changegamemode.Main
version: 1.0
name: ChangeGamemode
author: Im2Epic4U
description: Allows players on your server that are opped to change their gamemode.
commands:
  gm:
    description: Shows info about the plugin and how to use it.
    aliases: [gamemode]
  gmc:
    description: Changes your gamemode to creative.
  gms:
    description: Changes your gamemode to survival.
  gmsp:
    description: Changes your gamemode to spectator.
  gma:
    description: Changes your gamemode to adventure.
